//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrunTakipSistemi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBLPERSONEL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLPERSONEL()
        {
            this.TBLSATISLAR = new HashSet<TBLSATISLAR>();
        }
    
        public int? ID { get; set; }

        [Required(ErrorMessage ="Bu alanýný boþ býrakamýzsýnýz..")]
        public string AD { get; set; }

        [Required(ErrorMessage = "Bu alanýný boþ býrakamýzsýnýz..")]
        public string SOYAD { get; set; }

        [Required(ErrorMessage = "Bu alanýný boþ býrakamýzsýnýz..")]
        public string DEPARTMAN { get; set; }
        public Nullable<bool> DURUM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSATISLAR> TBLSATISLAR { get; set; }
    }
}
